[project]
name = "alcohol-pedagogics"
version = "0.1.0"
description = "Visualize the effects of alcohol, using the SUND Toolbox"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip>=25.1.1",
    "plotly>=6.0.1",
    "setuptools>=80.9.0",
    "streamlit>=1.45.0",
]
